version: "3.7"
name: database

services:
  db:
    container_name: ${DB_HOST:-database_db}
    image: postgres:14-alpine3.18
    environment:
      - POSTGRES_DB=${DB_NAME:-bot}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-p0stgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend_db_network


networks:
  backend_db_network:
    external: true

volumes:
  pgdata:
