# Generated by Django 5.1.1 on 2024-10-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не начата'), (2, 'В анализе'), (3, 'В работе'), (4, 'Завершена')], default=1, verbose_name='Статус'),
        ),
    ]
